.TH GIT-GEO 1 "December 22, 2010" "git-geo 0.9.2" "User Commands"
.SH NAME
git geo \- locate your source
.SH SYNOPSIS
.sp
.nf
\fIgit geo\fR setup
\fIgit geo\fR note [<commit>]
\fIgit geo\fR pull [<repository>]
\fIgit geo\fR push [\-\-all | \-\-mirror | \-\-tags] [\-n | \-\-dry\-run] [\-\-receive\-pack=<git\-receive\-pack>]
             [\-\-repo=<repository>] [\-f | \-\-force] [\-v | \-\-verbose] [\-u | \-\-set\-upstream]
             [<repository> [<refspec>\&...]]
\fIgit geo\fR sync [<repository>]
\fIgit geo\fR version
.fi
.SH DESCRIPTION
.sp
Attach location information to a commit. Setup a hook to automatically
attach location information to commits. Push and pull geocommits to or from a remote
repository\&.
.sp
\fIgit geo\fR requires access to WiFi\&.
.SH SUBCOMMANDS
.PP
setup
.RS 4
Setup a git post-commit hook in the current git repository to automatically
attach location information to your commits\&.
.RE
.PP
note
.RS 4
Obtain your current location and store it in a git note referencing the HEAD
commit. If <commit> is given, the command will store the location for the given
commit instead of HEAD\&.
.RE
.PP
pull
.RS 4
Pull geocommits from a repository and merge them\&.
.RE
.PP
push
.RS 4
Like \fIgit push\fR but also pushes geocommits. If necessary, git geo push will
merge geocommits\&.
.RE
.PP
sync
.RS 4
Pulls geocommits from the given repository. Merges the fetched geocommits with
the local geocommits and pushes the result to the repository\&.
.RE
.PP
version
.RS 4
Shows the current version of git geo\&.
.RE
.SH EXAMPLES
.sp
To setup an automatic geocommit hook type
.sp
.RS 4
.B cd myproject.git && git geo setup
.RE
.SH DISCUSSION
.sp
\fIgeo git\fR stores geocommits as git notes (see \fIgit help notes\fR). It uses
the "geocommit" namespace. \fIgit geo sync\fR will only push, pull and
merge geocommit notes.
.SH WEBSITE
.sp
For more information about geocommits and the geocommit format visit http://geocommit.com/
.SH SEE ALSO
git(1)
.SH AUTHOR
.sp
Written by Filip Noetzel, Nils Adermann, David Soria Parra
.SH NOTES
.sp
Requires git
1.6.5 or newer\&.
